AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TelegramToken:
    Type: String
  SupabaseUrl:
    Type: String
  SupabaseKey:
    Type: String

Resources:
  RoommateBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
      Events:
        TelegramWebhook:
          Type: HttpApi
          Properties:
            Path: /webhook
            Method: POST
Outputs:
  WebookApiUrl:
    Description: "URL for the Telegram Webhook"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/webhook"
