name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws-bot-iac
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # switching to Python 3.13 to support

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: SAM Build
        run: sam build --use-container

      - name: SAM Deploy
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name roommate-bot-stack \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              TelegramToken=${{ secrets.TELEGRAM_TOKEN }} \
              SupabaseUrl=${{ secrets.SUPABASE_URL }} \
              SupabaseKey=${{ secrets.SUPABASE_KEY }}

      - name: Show Webhook URL
        run: |
          echo "-------------------------------------------------------"
          echo "DEPLOYMENT COMPLETE!"
          echo "Your New Telegram Webhook URL is:"
          aws cloudformation describe-stacks \
            --stack-name roommate-bot-stack \
            --query "Stacks[0].Outputs[?OutputKey=='WebookApiUrl'].OutputValue" \
            --output text
          echo "-------------------------------------------------------"


      - name: Automate Telegram Webhook Connection
        run: |
          echo "Fetching active endpoint from CloudFormation..."
          
          # 1. Capture the live endpoint URL into a pipeline variable
          WEBHOOK_URL=$(aws cloudformation describe-stacks \
            --stack-name roommate-bot-stack \
            --query "Stacks[0].Outputs[?OutputKey=='WebookApiUrl'].OutputValue" \
            --output text)
          
          echo "Registering endpoint with Telegram API..."
          
          # 2. Execute a secure POST request to Telegram to instantly bind the webhook
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/setWebhook" \
            -H "Content-Type: application/json" \
            -d "{\"url\": \"$WEBHOOK_URL\", \"secret_token\": \"${{ secrets.TELEGRAM_SECRET_TOKEN }}\"}"
